name: 'clippy with reviewdog'
description: 'run clippy with reviewdog'

author: '@sksat'
branding:
  color: orange
  icon: check

inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
    required: true
  working_directory:
    description: 'clippy working directory'
    required: false
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'clippy'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'warning'
    required: true
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
    required: true
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
    required: true
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
    required: true
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
    required: false
  clippy_flags:
    description: 'Additional clippy flags'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: install reviewdog
      shell: bash
      env:
        # datasource=github-releases
        REVIEWDOG_REPO: "reviewdog/reviewdog"
        REVIEWDOG_VERSION: "v0.17.0"
      run: |
        curl -sfL "https://raw.githubusercontent.com/${REVIEWDOG_REPO}/master/install.sh" \
          | sh -s -- -b /usr/local/bin/ "${REVIEWDOG_VERSION}"

    - name: install clippy-reviewdog-filter
      shell: bash
      env:
        # datasource=github-releases
        CLIPPY_REVIEWDOG_FILTER_REPO: "qnighy/clippy-reviewdog-filter"
        CLIPPY_REVIEWDOG_FILTER_VERSION: "v0.1.4"
      run: |
        curl -sLJO "https://github.com/${CLIPPY_REVIEWDOG_FILTER_REPO}/releases/download/${CLIPPY_REVIEWDOG_FILTER_VERSION}/clippy-reviewdog-filter-x86_64-unknown-linux-musl"
        mv clippy-reviewdog-filter-x86_64-unknown-linux-musl /usr/local/bin/clippy-reviewdog-filter
        chmod +x /usr/local/bin/clippy-reviewdog-filter
        clippy-reviewdog-filter --version

    - name: clippy & reviewdog
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
        INPUT_WORKDIR: ${{ inputs.working_directory }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_CLIPPY_FLAGS: ${{ inputs.clippy_flags }}
