name: test action-clippy

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: install clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: check clippy version
        run: cargo clippy --version

      - uses: ./
        with:
          working_directory: ./test
          level: warning
          reporter: github-check
          filter_mode: nofilter
